<a href="https://colab.research.google.com/github/Arun-NriDegree/MINI-PROJECTS/blob/main/Working_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import pandas as pd

In [6]:
datasetpath = '/content/retail_transactions.csv'
df = pd.read_csv(datasetpath)

In [8]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [12]:
df.describe()

          StoreID   CustomerID   ProductID    Quantity      Price   Discount
count  100.000000   100.000000  100.000000  100.000000  100.00000  75.000000
mean   102.730000  1552.520000  554.390000    5.370000  282.15000   7.733333
std      1.384291   268.295461   28.544098    3.013957  140.19938   5.652871
min    101.000000  1013.000000  501.000000    1.000000   50.00000   0.000000
25%    101.000000  1310.250000  529.750000    3.000000  165.75000   2.500000
50%    103.000000  1534.000000  554.000000    5.500000  280.00000  10.000000
75%    104.000000  1800.750000  579.500000    8.000000  415.25000  12.500000
max    105.000000  1983.000000  600.000000   10.000000  500.00000  15.000000

In [13]:
df.columns

Index(['TransactionID', 'TransactionDate', 'StoreID', 'CustomerID',
       'ProductID', 'ProductCategory', 'Quantity', 'Price', 'PaymentType',
       'Discount'],
      dtype='object')

In [20]:
df['Transaction'] = pd.to_datetime(df['TransactionDate'])

In [21]:
retail_df=df

In [22]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,Transaction
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,2024-01-01
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,2024-01-02
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN,2024-01-03
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,2024-01-04
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,2024-01-05
...,...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,2024-04-05
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,2024-04-06
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0,2024-04-07
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,2024-04-08
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,2024-04-09

In [23]:
print("First 20 rows of the DataFrame:")
print(df.head(20))

First 20 rows of the DataFrame:
   TransactionID TransactionDate  StoreID  CustomerID  ProductID  \
0           T001      2024-01-01      102        1646        545
1           T002      2024-01-02      103        1226        542
2           T003      2024-01-03      102        1515        593
3           T004      2024-01-04      103        1793        560
4           T005      2024-01-05      105        1864        523
5           T006      2024-01-06      103        1836        515
6           T007      2024-01-07      103        1983        586
7           T008      2024-01-08      101        1806        569
8           T009      2024-01-09      101        1925        548
9           T010      2024-01-10      101        1711        565
10          T011      2024-01-11      103        1276        565
11          T012      2024-01-12      101        1486        523
12          T013      2024-01-13      103        1597        516
13          T014      2024-01-14      101        1462        520
14          T015      2024-01-15      104        1668        581
15          T016      2024-01-16      101        1278        594
16          T017      2024-01-17      101        1522        502
17          T018      2024-01-18      102        1199        565
18          T019      2024-01-19      101        1734        599
19          T020      2024-01-20      101        1724        583

   ProductCategory  Quantity  Price PaymentType  Discount Transaction
0      Electronics         1    150      Credit      15.0  2024-01-01
1             Toys         2    317       Debit      10.0  2024-01-02
2      Electronics         5    165       Debit       NaN  2024-01-03
3        Furniture         6    496       Debit      10.0  2024-01-04
4          Grocery        10    166       Debit       0.0  2024-01-05
5          Grocery         9    227       Debit       NaN  2024-01-06
6      Electronics         1    170      Credit       NaN  2024-01-07
7             Toys         4    500       Debit       0.0  2024-01-08
8          Apparel         7    217        Cash      10.0  2024-01-09
9        Furniture         3    466       Debit       5.0  2024-01-10
10       Furniture         1    321        Cash       NaN  2024-01-11
11            Toys         8    426      Credit       5.0  2024-01-12
12            Toys         5    262        Cash      15.0  2024-01-13
13     Electronics        10    218        Cash       NaN  2024-01-14
14            Toys         4    201       Debit      15.0  2024-01-15
15            Toys         8    416      Credit       0.0  2024-01-16
16       Furniture         6    190       Debit      10.0  2024-01-17
17         Apparel         6    495      Credit       0.0  2024-01-18
18         Apparel         9     55       Debit       0.0  2024-01-19
19       Furniture         3    447      Credit       NaN  2024-01-20

In [24]:
print("\nDataFrame Info:")
print(retail_df.info())

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    100 non-null    object
 1   TransactionDate  100 non-null    object
 2   StoreID          100 non-null    int64
 3   CustomerID       100 non-null    int64
 4   ProductID        100 non-null    int64
 5   ProductCategory  100 non-null    object
 6   Quantity         100 non-null    int64
 7   Price            100 non-null    int64
 8   PaymentType      100 non-null    object
 9   Discount         75 non-null     float64
 10  Transaction      100 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(5), object(4)
memory usage: 8.7+ KB
None

In [25]:
print("\nDescriptive Statistics:")
print(retail_df.describe())

Descriptive Statistics:
          StoreID   CustomerID   ProductID    Quantity      Price   Discount  \
count  100.000000   100.000000  100.000000  100.000000  100.00000  75.000000
mean   102.730000  1552.520000  554.390000    5.370000  282.15000   7.733333
min    101.000000  1013.000000  501.000000    1.000000   50.00000   0.000000
25%    101.000000  1310.250000  529.750000    3.000000  165.75000   2.500000
50%    103.000000  1534.000000  554.000000    5.500000  280.00000  10.000000
75%    104.000000  1800.750000  579.500000    8.000000  415.25000  12.500000
max    105.000000  1983.000000  600.000000   10.000000  500.00000  15.000000
std      1.384291   268.295461   28.544098    3.013957  140.19938   5.652871

               Transaction
count                  100
mean   2024-02-19 12:00:00
min    2024-01-01 00:00:00
25%    2024-01-25 18:00:00
50%    2024-02-19 12:00:00
75%    2024-03-15 06:00:00
max    2024-04-09 00:00:00
std                    NaN

In [33]:
print("\nMissing Values in Each Column:")
print(retail_df.isnull().sum())

Missing Values in Each Column:
TransactionID       0
TransactionDate     0
StoreID             0
CustomerID          0
ProductID           0
ProductCategory     0
Quantity            0
Price               0
PaymentType         0
Discount           25
Transaction         0
dtype: int64

In [34]:
retail_df['Discount'] = retail_df['Discount'].fillna(0)

In [35]:
retail_df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,Transaction
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,2024-01-01
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,2024-01-02
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,0.0,2024-01-03
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,2024-01-04
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,2024-01-05
...,...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,2024-04-05
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,2024-04-06
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0,2024-04-07
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,2024-04-08
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,2024-04-09